author = "Linux Gaming Central"
description = ""
menu_position = "TopLeft"
font_color = "WHITE"
cursor_color = "PURPLE"
background_scroll_speed = "OFF"
color_shift_speed = "OFF"
bgm_track = "majoras_mask_bgm.ogg"
logo_selection = "None"
background_selection = "majoras_mask_background.png"
font_selection = "majoras_mask_font.ttf"
sfx_pack = "majoras_mask_sfx"
