author = "Linux Gaming Central"
description = "Smash Bros. 64 with lo-fi music by Lofi Lia!"
menu_position = "Center"
font_color = "RED"
cursor_color = "YELLOW"
background_scroll_speed = "OFF"
color_shift_speed = "NORMAL"
bgm_track = "smash_bgm.ogg"
logo_selection = "smash_logo.png"
background_selection = "smash_background.png"
font_selection = "smash_font.ttf"
sfx_pack = "smash_sfx"
