author = "Linux Gaming Central"
description = ""
menu_position = "BottomLeft"
font_color = "YELLOW"
cursor_color = "YELLOW"
background_scroll_speed = "OFF"
color_shift_speed = "OFF"
bgm_track = "twilight_princess_bgm.ogg"
logo_selection = "None"
background_selection = "twilight_princess_background.png"
font_selection = "twilight_princess_font.ttf"
sfx_pack = "twilight_princess_sfx"
