author = "Linux Gaming Central"
description = ""
menu_position = "BottomLeft"
font_color = "WHITE"
cursor_color = "YELLOW"
background_scroll_speed = "OFF"
color_shift_speed = "SLOW"
bgm_track = "metroid_prime_bgm.ogg"
logo_selection = "None"
background_selection = "metroid_prime_background.png"
font_selection = "metroid_prime_font.ttf"
sfx_pack = "metroid_prime_sfx"
