author = "Linux Gaming Central"
description = "A throwback to the Wii homebrew days!"
menu_position = "Center"
font_color = "BLACK"
cursor_color = "BLACK"
background_scroll_speed = "OFF"
color_shift_speed = "OFF"
bgm_track = "uloader_bgm.ogg"
logo_selection = "uloader_logo.png"
background_selection = "uloader_background.png"
font_selection = "uloader_font.ttf"
sfx_pack = "uloader_sfx"
