author = "Linux Gaming Central"
description = ""
menu_position = "Center"
font_color = "BLUE"
cursor_color = "WHITE"
background_scroll_speed = "OFF"
color_shift_speed = "OFF"
bgm_track = "star-fox-64_bgm.ogg"
logo_selection = "None"
background_selection = "star-fox-64_background.png"
font_selection = "star-fox-64_font.ttf"
sfx_pack = "star-fox-64_sfx"
