author = "Linux Gaming Central"
description = ""
menu_position = "BottomLeft"
font_color = "WHITE"
cursor_color = "BLUE"
background_scroll_speed = "OFF"
color_shift_speed = "OFF"
bgm_track = "sonic-adventure-2_bgm.ogg"
logo_selection = "None"
background_selection = "sonic-adventure-2_background.png"
font_selection = "sonic-adventure-2_font.ttf"
sfx_pack = "sonic-adventure-2_sfx"
