author = "Linux Gaming Central"
description = ""
menu_position = "BottomLeft"
font_color = "GREEN"
cursor_color = "ORANGE"
background_scroll_speed = "NORMAL"
color_shift_speed = "NORMAL"
bgm_track = "sonic_mega_collection_bgm.ogg"
logo_selection = "sonic_mega_collection_logo.png"
background_selection = "sonic_mega_collection_background.png"
font_selection = "sonic_mega_collection_font.ttf"
sfx_pack = "sonic_mega_collection_sfx"
