author = "Linux Gaming Central"
description = ""
menu_position = "Center"
font_color = "WHITE"
cursor_color = "GREEN"
background_scroll_speed = "NORMAL"
color_shift_speed = "NORMAL"
bgm_track = "None"
logo_selection = "None"
background_selection = "dreamcast_background.png"
font_selection = "dreamcast_font.ttf"
sfx_pack = "dreamcast_sfx"
