author = "Linux Gaming Central"
description = ""
menu_position = "BottomRight"
font_color = "WHITE"
cursor_color = "PURPLE"
background_scroll_speed = "OFF"
color_shift_speed = "OFF"
bgm_track = "gamecube_bgm.ogg"
logo_selection = "gamecube_logo.png"
background_selection = "None"
font_selection = "gamecube_font.ttf"
sfx_pack = "gamecube_sfx"
