author = "Linux Gaming Central"
description = ""
menu_position = "TopLeft"
font_color = "WHITE"
cursor_color = "YELLOW"
background_scroll_speed = "OFF"
color_shift_speed = "OFF"
bgm_track = "sonic_3_bgm.ogg"
logo_selection = "None"
background_selection = "sonic_3_background.png"
font_selection = "sonic_3_font.ttf"
sfx_pack = "sonic_3_sfx"
