author = "Linux Gaming Central"
description = ""
menu_position = "TopLeft"
font_color = "BLUE"
cursor_color = "BLUE"
background_scroll_speed = "OFF"
color_shift_speed = "OFF"
bgm_track = "wii_bgm.ogg"
logo_selection = "wii_logo.png"
background_selection = "wii_background.png"
font_selection = "wii_font.ttf"
sfx_pack = "wii_sfx"
