author = "Linux Gaming Central"
description = "Throwback to the Wii homebrew days!"
menu_position = "Center"
font_color = "BLACK"
cursor_color = "YELLOW"
background_scroll_speed = "NORMAL"
color_shift_speed = "OFF"
bgm_track = "snes9xgx_bgm.ogg"
logo_selection = "None"
background_selection = "snes9xgx_background.png"
font_selection = "snes9xgx_font.ttf"
sfx_pack = "snes9xgx_sfx"
