author = "Linux Gaming Central"
description = "A love letter to Gardiner Bryant, YouTuber and creator of Dudelings: Arcade Sportsball"
menu_position = "BottomLeft"
font_color = "YELLOW"
cursor_color = "WHITE"
background_scroll_speed = "NORMAL"
color_shift_speed = "OFF"
bgm_track = "dudelings_bgm.ogg"
logo_selection = "dudelings_logo.png"
background_selection = "dudelings_background.png"
font_selection = "dudelings_font.ttf"
sfx_pack = "dudelings_sfx"
