author = "Linux Gaming Central"
description = "BGM by Gamerfreak5665"
menu_position = "BottomRight"
font_color = "WHITE"
cursor_color = "YELLOW"
background_scroll_speed = "OFF"
color_shift_speed = "OFF"
bgm_track = "f-zero_bgm.ogg"
logo_selection = "None"
background_selection = "f-zero_background.png"
font_selection = "f-zero_font.ttf"
sfx_pack = "f-zero_sfx"
